improbable-eng/kedge

Dockerfile
server/Dockerfile

A basic Dockerfile that builds the Kedge server binary against Go 1.8.

Add Dockerfile

---

proto/kedge/config/common/resolvers/resolvers.proto
server/README.md
server/configs.go
server/main.go

Made kedge config parsing more resilient on user errors.

---

.gitmodules
.travis.yml
README.md

Used tool: https://github.com/kovetskiy/manul

Added initial vendoring using submodules.

---

winch/README.md
winch/integration_test.go
winch/pac.go
winch/server/main.go

Added auto-generated PAC handler.

---

http/lbtransport/transport_test.go

This is due to only "statistical" guarantee of round robin behaviour.

Fixed flaky tests - making requirement much softer.

---

.gitignore
README.md
http/director/proxy.go
lib/http/ctxtags/tags.go
lib/http/tripperware/auth.go
lib/http/tripperware/tripperware_test.go
server/main.go
server/oidc.go
server/tls.go
winch/README.md

[Auth Part 1]  Added OIDC Auth for kedge server side.

---

.gitmodules
Dockerfile
build_image.sh
http/integration_test.go
server/main.go
server/version.go

Added version endpoint and Dockerfile.

---

.gitmodules
server/README.md
server/main.go
server/oidc.go

Added optional OIDC auth for kedge debug endpoints.

---

http/director/proxy.go
proto/kedge/config/http/backends/backend.proto

Fixed small nits in comment and err output.

---

.gitmodules
http/client/client.go
http/director/proxy.go
lib/auth/oidc.go
lib/http/tripperware/auth.go
lib/http/tripperware/map.go
lib/http/tripperware/route.go
lib/http/tripperware/tripperware.go
lib/http/tripperware/tripperware_test.go
server/main.go
server/tls.go
winch/routes.go
winch/server/main.go
winch/server/tls.go

PTAL @kdima
+ Fixed critical bug

Support custom TLS options on winch

---

README.md

Added item to wishlist.

---

.gitmodules
CHANGELOG.md
lib/sharedflags/set.go
server/logstash_formatter.go
server/main.go
winch/lib/integration_test.go

Added optional remote logging to kedge.

---

.travis.yml
lib/logstash/conn.go
lib/logstash/conn_test.go
lib/logstash/logstash.go
lib/logstash/logstash_formatter.go
lib/logstash/reporter.go
server/main.go

More Features:
* Reconnect logic with backoff.
* Async logging
* Metrics
PTAL @kdima @joshpmcghee 

Added working logstash remote logger.

---

.travis.yml
grpc/client/client.go
http/integration_test.go
lib/auth/gcp.go
lib/http/tripperware/auth.go
lib/http/tripperware/map.go
lib/http/tripperware/route.go
lib/http/tripperware/tripperware.go
lib/http/tripperware/tripperware_test.go
lib/map/iface.go
lib/map/route.go
lib/map/simple.go
lib/map/single.go
lib/map/suffix.go
lib/map/suffix_test.go
proto/winch/config/mapper.proto
server/main.go
winch/lib/integration_test.go
winch/lib/proxy.go
winch/lib/routes.go
winch/lib/routes_test.go
winch/main.go

Extended routing with Port matching on winch.

---

http/backendpool/backend.go
http/backendpool/dynamic.go
http/backendpool/dynamic_test.go
http/director/proxy.go
http/integration_test.go
http/lbtransport/transport.go
http/lbtransport/transport_test.go
lib/resolvers/k8s/client.go
lib/resolvers/k8s/flags.go
lib/resolvers/k8s/resolver.go
lib/resolvers/k8s/streamer.go
lib/resolvers/k8s/streamer_test.go
lib/resolvers/k8s/watcher.go
server/configs.go
server/main.go

Assumption: watcher.Next errors are irrecoverable.

Refactored k8s resolver to be complaint with watcher.Next interface assumption

---

http/lbtransport/transport.go

Fixed backoff retry on lbtransport.

---

server/main.go
tools/discovery/main.go

[5] Attached dynamic routing discovery and added cmd tool.

---

glide.lock
grpc/backendpool/dynamic.go
grpc/backendpool/dynamic_test.go
http/backendpool/dynamic.go
http/backendpool/dynamic_test.go
http/director/proxy.go
lib/metrics/backend_configuration.go
server/configs.go
server/main.go

Added more metrics!

---

CHANGELOG.md
glide.lock
http/backendpool/backend.go
http/director/proxy.go
http/integration_test.go
http/lbtransport/transport.go
http/lbtransport/transport_test.go
lib/discovery/updater.go
lib/http/ctxtags/tags.go
lib/http/header/header.go
lib/http/header/request.go
lib/http/header/response.go
lib/http/tripperware/debug.go
lib/metrics/kedge_error.go
lib/reporter/errtypes/errtypes.go
lib/reporter/reporter.go
server/main.go
winch/lib/proxy.go
winch/main.go

Also:
- Added request ID from winch to kedge.
- Added special debug mode to log more if winch sets special header.

Added proxy-wise error reporting to understand more from metric and logging perspective.

---

CHANGELOG.md
grpc/backendpool/dynamic.go
http/lbtransport/policy.go
http/lbtransport/transport.go
lib/discovery/discovery.go
lib/discovery/streamer.go
lib/resolvers/k8s/streamer.go
lib/resolvers/k8s/streamer_test.go
lib/resolvers/k8s/watcher.go
server/configs.go

Fixed ~3 potential go routine leaks. Improved logs.

---

glide.lock
grpc/backendpool/backend.go
grpc/backendpool/dynamic.go
http/backendpool/backend.go
http/backendpool/dynamic.go
http/backendpool/pool.go
http/backendpool/static.go
http/integration_test.go
http/lbtransport/policy.go
http/lbtransport/policy_test.go
http/lbtransport/transport.go
http/lbtransport/transport_test.go
lib/discovery/discovery.go
lib/discovery/streamer.go
lib/discovery/updater_test.go
lib/resolvers/k8s/streamer.go
winch/lib/integration_test.go

+ fixed potential go routine leak.

Add update aggregation for discovery to stop doing so many unnecessary connection interruptions.

---

CHANGELOG.md
glide.lock
winch/main.go

Added CORS for winch

---

CHANGELOG.md
Dockerfile_loadtest
server/main.go
server/term.go

Added graceful shutdown for seemless k8s rollouts.

---

Dockerfile
pkg/kedge/grpc/backendpool/backend.go
pkg/kedge/http/backendpool/backend.go
pkg/resolvers/host/host.go

Fixed host resolver.

---

CHANGELOG.md
pkg/kedge/grpc/director/director.go

Set gRPC single metadata item before actual cloning.

---

README.md

docs: Moved wishlist to GitHub issues.

---

Gopkg.lock
cmd/kedge/main.go
cmd/winch/main.go
pkg/kedge/grpc/integration_test.go

kedge: Improved kEdge cmd (moved to run.Group) + make format.

---

.gitignore
Gopkg.toml
Makefile

Branching from #95 from @Bplotka and moving build dependencies into dep.

Fixed protogen script using dep

---

Gopkg.toml

fixing typo

---

cmd/winch/main.go
pkg/tls/client.go
proto/kedge/config/common/resolvers/resolvers.proto

Moved not important log message to debug.

---

Gopkg.lock
Gopkg.toml

deps: pin OIDC client lib version.

---

pkg/resolvers/k8s/watcher.go
pkg/resolvers/k8s/watcher_test.go

Tested with standalone resolver during rollout + unit tests.

k8sresolver: Fixed critical bug v2. We now understand modified event type. (:

---

pkg/resolvers/k8s/watcher.go

k8sresolver: Do not log error on context cancel

---

pkg/http/ctxtags/tags.go
pkg/kedge/http/lbtransport/policy.go
pkg/kedge/http/lbtransport/transport.go

tripper: Added resolved addr tag and better error message.

---

cmd/winch/main.go

winch: Added monitoring endpoint on different port for sidecar purposes.

---

pkg/winch/grpc/proxy.go

winch: Fixed potential nil pointer exception.

---

cmd/kedge/main.go
cmd/winch/main.go

winch: Allow changing metric path.

---

pkg/resolvers/host/host.go
pkg/resolvers/host/host_test.go
pkg/resolvers/srv/srv.go
pkg/resolvers/srv/srv_test.go

Fixed critical bug in host resolver causing constant DNS polling.

---

.travis.yml
pkg/reporter/reporter.go
pkg/tls/client.go
pkg/winch/pac.go

Enabled to specify PAC file from disk.

---

.travis.yml
Makefile
cmd/kedge/term.go
pkg/e2e/spinup_test.go
pkg/kedge/http/lbtransport/transport.go
pkg/kedge/http/lbtransport/transport_test.go

- Added Windows build instructions to the Travis file
- Fixed compile errors
- Fixed tests
Ran the test suite.

Building on Windows
